version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - 8000:8000

  tests:
    build:
      context: .
    command: /bin/sh -c "pytest -p no:warnings"

    depends_on:
      - server
