version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - 8000:8000

  tests:
    build:
      context: .
      target: test
    depends_on:
      - server
    command: /bin/bash -c "pytest -p no:warnings &&  curl --fail http://server:8000/metrics || exit 1"
